version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hospital_transport_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: HospitalTransportDB
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hospital_network

  api:
    build:
      context: .
      dockerfile: HospitalTransport.API/Dockerfile
    container_name: hospital_transport_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=HospitalTransportDB;Username=postgres;Password=postgres
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - postgres
    networks:
      - hospital_network

volumes:
  postgres_data:

networks:
  hospital_network:
    driver: bridge