--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13 (Debian 15.13-1.pgdg120+1)
-- Dumped by pg_dump version 15.13 (Debian 15.13-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Appointments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Appointments" (
    "Id" uuid NOT NULL,
    "PatientId" uuid NOT NULL,
    "MedicalRecordNumber" character varying(50) NOT NULL,
    "DestinationHospital" character varying(200) NOT NULL,
    "TreatmentType" integer NOT NULL,
    "TreatmentTypeOther" character varying(200),
    "IsPriority" boolean NOT NULL,
    "SeatNumber" integer NOT NULL,
    "AppointmentDate" timestamp without time zone NOT NULL,
    "CompanionId" uuid,
    "CompanionSeatNumber" integer,
    "CreatedByUserId" uuid NOT NULL,
    "IsTicketPrinted" boolean NOT NULL,
    "PrintedAt" timestamp without time zone,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."Appointments" OWNER TO postgres;

--
-- Name: Patients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Patients" (
    "Id" uuid NOT NULL,
    "FullName" character varying(200) NOT NULL,
    "RG" character varying(20) NOT NULL,
    "CPF" character varying(14) NOT NULL,
    "Age" integer NOT NULL,
    "BirthDate" date NOT NULL,
    "SusCardNumber" character varying(15) NOT NULL,
    "PhoneNumber" character varying(20) NOT NULL,
    "MotherName" character varying(200) NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."Patients" OWNER TO postgres;

--
-- Name: SystemControl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SystemControl" (
    "Id" integer NOT NULL,
    "IsEnabled" boolean NOT NULL,
    "Message" character varying(500),
    "LastChanged" timestamp without time zone NOT NULL
);


ALTER TABLE public."SystemControl" OWNER TO postgres;

--
-- Name: SystemControl_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SystemControl" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SystemControl_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" uuid NOT NULL,
    "FullName" character varying(200) NOT NULL,
    "Username" character varying(100) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" character varying(50) NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Appointments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Appointments" ("Id", "PatientId", "MedicalRecordNumber", "DestinationHospital", "TreatmentType", "TreatmentTypeOther", "IsPriority", "SeatNumber", "AppointmentDate", "CompanionId", "CompanionSeatNumber", "CreatedByUserId", "IsTicketPrinted", "PrintedAt", "CreatedAt", "UpdatedAt", "IsActive") FROM stdin;
5abc46a2-1226-4c38-b4fc-62d39c084e44	dca1cb99-b468-4313-8f8c-7c7ca2d34172	206	IJF	1	\N	t	1	2025-10-22 12:00:00	\N	\N	8894d286-47a6-4ee2-a32a-65dabc2bc4cc	t	2025-10-08 00:46:06.274302	2025-10-07 14:06:24.982014	\N	t
bab805a3-73ce-4041-875b-43defa7c5872	22443d97-afda-4c7b-b7f8-578093bd4a9a	2389502	hospital icc	1	\N	f	16	2025-10-29 08:00:00	\N	\N	8894d286-47a6-4ee2-a32a-65dabc2bc4cc	t	2025-10-08 18:41:58.009425	2025-10-08 18:41:31.695372	\N	t
3d59277d-7697-4db7-8f10-614e178fc569	88b9efed-f378-4ed5-8aec-9a318ceec9b4	801	Hospital Municipal de Fortaleza	1	\N	f	12	2025-10-29 12:00:00	\N	\N	8894d286-47a6-4ee2-a32a-65dabc2bc4cc	t	2025-10-08 19:17:45.663757	2025-10-08 18:06:16.541047	\N	t
2b2db2e7-c7ec-42fc-89d2-e501408879ee	1adf235c-65c0-4a80-8a64-fef402ca4668	201	Hospital Regional de Quixeramobim	3	\N	f	23	2025-10-29 12:00:00	dca1cb99-b468-4313-8f8c-7c7ca2d34172	35	9452dc26-7e06-4d7b-b0d7-4ad5f3d47129	t	2025-10-08 19:25:34.576802	2025-10-07 14:21:54.639984	\N	t
\.


--
-- Data for Name: Patients; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Patients" ("Id", "FullName", "RG", "CPF", "Age", "BirthDate", "SusCardNumber", "PhoneNumber", "MotherName", "CreatedAt", "UpdatedAt", "IsActive") FROM stdin;
dca1cb99-b468-4313-8f8c-7c7ca2d34172	Vinicius Sales	2006019192061	07198352324	26	1999-03-22	07198352324	88999755789	Onélia Alves	2025-10-07 14:04:53.072989	\N	t
1adf235c-65c0-4a80-8a64-fef402ca4668	Maria das Dores Araujo Mota	20071368528	05429241377	33	1991-10-14	05429241377	88981314756	Iraci Araujo Silva	2025-10-07 14:20:09.815113	\N	t
88b9efed-f378-4ed5-8aec-9a318ceec9b4	Camila Gomes de Freitas	44820874837	44820874837	22	2002-12-08	44820874837	88996019939	Angela Mateus Gomes	2025-10-08 18:00:18.054687	\N	t
22443d97-afda-4c7b-b7f8-578093bd4a9a	natalia vitoria ferreira	05709763322	05709763322	32	1993-08-08	708402714017866	88996143998	maria de fatima ferreira	2025-10-08 18:38:07.173525	\N	t
3989948f-dd3f-4b8e-82b8-7430442e43b0	Keila Bezerra Lopes Noronha	04013872323	04013872323	35	1990-07-08	04013872323	88996672100	Merci Bezerra dos Santos	2025-10-09 11:02:07.33437	\N	t
\.


--
-- Data for Name: SystemControl; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."SystemControl" ("Id", "IsEnabled", "Message", "LastChanged") FROM stdin;
1	t	Sistema operando normalmente	2025-10-07 11:33:22.573055
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "FullName", "Username", "PasswordHash", "Role", "CreatedAt", "UpdatedAt", "IsActive") FROM stdin;
8894d286-47a6-4ee2-a32a-65dabc2bc4cc	Administrador do Sistema	admin	YWRtaW4xMjM=	Admin	2025-10-07 11:33:22.573048	\N	t
9452dc26-7e06-4d7b-b0d7-4ad5f3d47129	Alzeneide Noronha Pereira	neide.noronha	MTIzNDU2	AssistenteSocial	2025-10-07 14:18:30.488366	\N	t
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20251002132720_InitialCreate	8.0.0
20251002185423_UpdateBirthDateToDateOnly	8.0.0
20251007113322_AddSystemControlTable	8.0.0
\.


--
-- Name: SystemControl_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SystemControl_Id_seq"', 2, false);


--
-- Name: Appointments PK_Appointments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Appointments"
    ADD CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id");


--
-- Name: Patients PK_Patients; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Patients"
    ADD CONSTRAINT "PK_Patients" PRIMARY KEY ("Id");


--
-- Name: SystemControl PK_SystemControl; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SystemControl"
    ADD CONSTRAINT "PK_SystemControl" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Appointments_AppointmentDate; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Appointments_AppointmentDate" ON public."Appointments" USING btree ("AppointmentDate");


--
-- Name: IX_Appointments_AppointmentDate_SeatNumber; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Appointments_AppointmentDate_SeatNumber" ON public."Appointments" USING btree ("AppointmentDate", "SeatNumber");


--
-- Name: IX_Appointments_CompanionId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Appointments_CompanionId" ON public."Appointments" USING btree ("CompanionId");


--
-- Name: IX_Appointments_CreatedByUserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Appointments_CreatedByUserId" ON public."Appointments" USING btree ("CreatedByUserId");


--
-- Name: IX_Appointments_PatientId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Appointments_PatientId" ON public."Appointments" USING btree ("PatientId");


--
-- Name: IX_Patients_CPF; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Patients_CPF" ON public."Patients" USING btree ("CPF");


--
-- Name: IX_Patients_SusCardNumber; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Patients_SusCardNumber" ON public."Patients" USING btree ("SusCardNumber");


--
-- Name: IX_Users_Username; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_Username" ON public."Users" USING btree ("Username");


--
-- Name: Appointments FK_Appointments_Patients_CompanionId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Appointments"
    ADD CONSTRAINT "FK_Appointments_Patients_CompanionId" FOREIGN KEY ("CompanionId") REFERENCES public."Patients"("Id") ON DELETE RESTRICT;


--
-- Name: Appointments FK_Appointments_Patients_PatientId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Appointments"
    ADD CONSTRAINT "FK_Appointments_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("Id") ON DELETE RESTRICT;


--
-- Name: Appointments FK_Appointments_Users_CreatedByUserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Appointments"
    ADD CONSTRAINT "FK_Appointments_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES public."Users"("Id") ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

